* Цель
Мы разрабатываем сервис, который позволяет блоггерам встраивать в свои
сайты виджеты с определенными товарами, которые они могут через свой
сайт продавать и получать комиссию.

* Процесс
Поставщики предоставляеют нам товары, по своим "ценам поставщика". Мы
заносим их в нашу систему систему, добавляем свою наценку и
предоставляем возможность Блоггерам продавать эти товары на своих
сайте с добавлением их наценки. Блоггеры также отслеживают свои
продажи через предоставляемый нами интерфейс.

Поэтому мы выделяем сущности и роли и описываем их взаимодействие.

* Сущности

** Виджет
Это блок на странице сайта Блоггера, который содержит
картинку товара, цену и кнопку купить.
*** Дата создания
*** Кол-во денег, заработанных на товаре
*** Наименование товара
*** Сколько раз товар был продан

** Товар
Это то что мы продаем. Товары предоставляют нам Поставщики, а Блоггеры
их продают.
*** Название
*** Цена
*** Категория
*** Поставщик
*** Стоимость
*** Минимальная наценка
*** Описание
*** Изображение (м.б. много?)

** Заказ
Это то что формируется, когда Посетитель блога нажимает на Виджете
кнопку "купить"
*** Идентификатор
*** Дата
*** Статус
**** Невыполнен
**** Выполнен и оплачен
**** Доставлен
**** Период возврата средств исчерпан <?>
**** ...<?>


* Роли

** Блоггер
Это человек, зарегистрированный в системе и продающий через свой сайт,
товары, которые мы получаем от поставщиков.

*** Логиниццо
*** Видит баланс (заработанная часть / замороженная часть)
*** Видит свои виджеты
*** Создает виджеты
*** Видит список заказов, прошедших через сайт
*** Видит список продаж по каждому виджету
*** Отфильтровать список заказов по (виджету / товару / категории / поставщику / по кол-ву товаров в заказе / статусу
*** Видит по заказу:
**** Стоимость
**** Вознаграждение
**** Замороженное вознаграждение
**** Причина заморозки
***** Еще не истек период возврата
***** Фрод
***** ...<?>
**** Статус
**** Статус доставки
**** Товары в заказе
**** Поставщик
****
*** Создает виджет по шаблону (расположение элементов и цветовую схему, выбирает товар для виджета)
*** Видеть список товаров и искать в нем по имени и описанию, фильтрация по остальным полям.
*** Меняет описания и названия товаров в виджете (т.е. по умолчанию в виджет попадают описание товаров)
*** Получает код для своей CMS
*** Вывести деньги, но не меньше минимального уровня.
*** Смотреть данные по выводу денег прозрачно еще до вывода
*** Обратная связь
** Оператор заказа
** Модератор товаров
** Покупатель
